### PR TITLE
add: Local Palette Build Step + Queue Fix!

### PR DESCRIPTION
**Pull request by coldenate**
In this PR, I made it my mission to add something in from https://github.com/catppuccin/remnote/pull/7#issuecomment-1437404265...

I addressed the concern of using a fetch to grab the color palette CSS file. I have implemented a build step in the `archive.yml` that handles the importing of the file. 

I also finally got to the Queue fixing on Desktop that I had known about for ~4 months. 😅

## Summary

- Fixed Queue
- Added a Local Palette Build Step
- Implemented some CSS to prepare for Remnote's alpha feature: Flashcard Home! 

Cheers!

### CODE REVIEW

**Comment by coldenate** [comment]
also, quick question, is #2 ready to be closed? I have fixed the errors mentioned in the issue.

**Review by justTOBBI — APPROVED** [review]

**Comment by justTOBBI** [comment]
If all points in the issue have been fixed, I dont think there is anything against closing the issue. Feel free to :D

**Comment by coldenate** [comment]
Oh ok! The button is disabled for me, does it work for you? @justTOBBI

**Comment by justTOBBI** [comment]
Oh ye, we dont have perms I think. @catppuccin/staff is there anything yall can do?

**Comment by coldenate** [comment]
Thank you! 🙏

**Comment by sgoudham** [comment]
Raised #9 for you guys

**Pull request merged**
