### PR TITLE
fix: Workflow Zip Folder Structure | misnomer in reqs

### PR DESCRIPTION
**Pull request by coldenate**
# oops

I may or may not have forgotten in the last pr to rename the images to logo.png... 😭 

This PR implements a better zip folder structure so Remnote can instantly accept it on the validation side of uploading, and I renamed the logo files to the required `logo.png` so they appeared. 

I have already uploaded the fix to Remnote, in part to test it, but also to get the patch out asap. I hope this was not awkward actions.

- [x] Implement local method of storing palette values. 

This PR should finally bring a close to #2.

### CODE REVIEW

**Comment by coldenate** [comment]
oh yes, the reason the workflow has failed is because I renamed the directory `frappé` to `frappe` because I noticed I was creating a lot of minor errors as I edited the repo.

**Comment by justTOBBI** [comment]
@coldenate so the Workflow should work now?

**Comment by coldenate** [comment]
Yes. I tested the code on my own machine and it seem to work and that's how I uploaded it to remnote.

**Comment by nekowinston** [comment]
Unrelated to this PR, but since this is a followup for #6:

How does Remnote handle remote CSS imports if you're offline?

**Comment by coldenate** [comment]
@nekowinston That's a good question, would it be optimal to add the local definitions back? I never thought about that. Thank you for pointing that out.

**Comment by nekowinston** [comment]
Yeah I'd be fine with that, bonus points if it's using some build step to bundle it. 😉

**Comment by coldenate** [comment]
For now, I'll work on just hardcoding the values in the file. I'll ask around on the Remnote discord to see if I can bundle the file in the zip and if it would properly import the file. @nekowinston

**Review by justTOBBI — APPROVED** [review]
Looks good. Thanks for carrying this repo :D

**Pull request merged**
